{
    'name': 'Bank Management System',
    'description': "Bank Management System",
    'version': '1.0',
    'depends': ['base',],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/sequence.xml',
        'reports/account_statement_report.xml',
        'views/bank_account_details.xml',
        'views/customer_details.xml',
        'views/transaction.xml',
        'views/deposit.xml',
        'views/withdraw.xml',
        'views/loan_application.xml',
        'views/loan_installment.xml',
        'views/loan_payment_history.xml',
        'reports/account_statement_report.xml',
    ],
    'application': True,
    'installable': True,
}
